### ISSUE TITLE
Write an about section for the website 

### ISSUE THREAD

**Issue by konsternacja** [f1lem0n/falscify#13]
*Please read the following instructions carefully.*

*Having detailed, yet not overcomplicated feedback will help us implement your idea efficiently.* 🚒

***Before suggesting a new feature, please search for a similar feature requests in the [issues section](https://github.com/f1lem0n/falscify/issues).*** 👀️

### Checklist ✅

- [x] I have read and consent to this project's [Code of Conduct](https://github.com/f1lem0n/falscify/blob/main/CODE_OF_CONDUCT.md).
- [x] I added a very descriptive title.
- [x] I searched through issues in this repository to find a similar feature request but did not find any.
- [x] I searched through **falscify** documentation and found no such feature available.

### Feature description 📖

*Please describe your idea briefly and state why it is important to implement it.*

Write an about section for the website  containing:
- mission
  - problem we are trying to solve
  - approach
- team

*Provide our team a list of changes/improvements we should take into consideration.*

This change is outside of codebase and will be posted as a comment down below.

### Additional comments 💬

*You can provide some additional information in this section.*

<br>

*Thank you for your contribution!* 🤖

**Comment by konsternacja** [comment]
##Problem we are trying to solve

The current crisis in science revolves around the issue of publication bias, where only positive results are often favored for publication. This creates a skewed representation of scientific research and can lead to a distortion of knowledge and understanding. By selectively publishing positive results, important negative findings or inconclusive studies are often overlooked, preventing a comprehensive understanding of a particular field. This bias can stem from various factors such as the pressure to publish in high-impact journals, the preference of journals for novel or groundbreaking results, and the tendency of researchers to prioritize positive outcomes. 

##Main goal

Falscify is here to serve the research community by publishing so called negative results. However, our platform is something much more than  a database of reports. Falscify is a platform that brings together scientists and allows them to show results that couldn’t be published. Our main goal is to show the world that the negative result is as much important as the positive result. By introducing Falscify we want to break the dogma of confirmatory science and enter an era of bias mitigation-focused science.

##Mission and Values

As a pioneer of bias mitigation-focused open access publishing, Falscify is based on the following values and guiding principles:
- Open Access
- Community
- Simplicity
- High Quality Service
- Transparency

##Passionate about science

The creators of this platform are two unwavering dreamers who possess a profound love for science. They strongly disagree with the current state of science and are determined to enact change.

##The name

Falscify is derived from the word "falsify," which means to demonstrate the falsehood of a statement or theory. Our aim is to demonstrate that these results are equally valid. We aspire to provide scientists with a platform where they can freely share such results and leverage the knowledge of others.

**Comment by f1lem0n** [comment]
I would change "negative results" to "statistically insignificant results". It is a more polite and also more precise way of calling them. And I think we should stick to that name - we are creating for professionals so let's be professional.

**Comment by f1lem0n** [comment]
Also a tip: in markdown you need to put spaces after # for it to work ;)
It doesn't matter here however because I write it in HTML anyways.

**Comment by f1lem0n** [comment]
I will close this one for now. I we need to change something we will reopen it.
